/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.ImageIcon;
import Classes.Boyfriend;

/**
 *
 * @author Asus
 */
public class ClotheSwapper extends javax.swing.JFrame {

    private final MainScreen mainScreen;
    Boyfriend player;

    /**
     * Creates new form ClotheSwopper
     *
     * @param m
     */
    public ClotheSwapper(MainScreen m) {
        initComponents();
        mainScreen = m;
        player = mainScreen.getPlayer();
    }

    private void checker() {
        switch (player.getShirt()) {
            case "walkingdead":
                background.setIcon(new ImageIcon(getClass().getResource("/Icons/walkingdead.png")));
                break;
            case "striped":
                background.setIcon(new ImageIcon(getClass().getResource("/Icons/striped shirt back.png")));
                break;
            case "orange":
                background.setIcon(new ImageIcon(getClass().getResource("/Icons/orange.png")));
                break;
            default:
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        walkingdeadButton = new javax.swing.JButton();
        strippedButton = new javax.swing.JButton();
        orangeButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);
        backButton.setBounds(20, 560, 73, 23);

        walkingdeadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/WalkingdeadShirt.png"))); // NOI18N
        walkingdeadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walkingdeadButtonActionPerformed(evt);
            }
        });
        jPanel1.add(walkingdeadButton);
        walkingdeadButton.setBounds(400, 20, 260, 170);

        strippedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/strip shirt.png"))); // NOI18N
        strippedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strippedButtonActionPerformed(evt);
            }
        });
        jPanel1.add(strippedButton);
        strippedButton.setBounds(400, 220, 260, 170);

        orangeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/OrangeShirt.png"))); // NOI18N
        orangeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orangeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(orangeButton);
        orangeButton.setBounds(400, 410, 260, 170);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/striped shirt back.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 700, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        switch (player.getShirt()) {
            case "walkingdead":
                mainScreen.left.setIcon(new ImageIcon(getClass().getResource("/Icons/walkingdeadPlayer.png")));
                mainScreen.center.setIcon(new ImageIcon(getClass().getResource("/Icons/walkingdeadPlayer.png")));
                mainScreen.right.setIcon(new ImageIcon(getClass().getResource("/Icons/walkingdeadPlayer.png")));
                break;
            case "orange":
                mainScreen.left.setIcon(new ImageIcon(getClass().getResource("/Icons/orangePlayer.png")));
                mainScreen.center.setIcon(new ImageIcon(getClass().getResource("/Icons/orangePlayer.png")));
                mainScreen.right.setIcon(new ImageIcon(getClass().getResource("/Icons/orangePlayer.png")));
                break;
            case "striped":
                mainScreen.left.setIcon(new ImageIcon(getClass().getResource("/Icons/striped.png")));
                mainScreen.center.setIcon(new ImageIcon(getClass().getResource("/Icons/striped.png")));
                mainScreen.right.setIcon(new ImageIcon(getClass().getResource("/Icons/striped.png")));
                break;
            default:
                break;
        }
        mainScreen.flag = true;
        mainScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void walkingdeadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walkingdeadButtonActionPerformed
        player.setShirt("walkingdead");
        checker();
    }//GEN-LAST:event_walkingdeadButtonActionPerformed

    private void strippedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strippedButtonActionPerformed
        player.setShirt("striped");
        checker();
    }//GEN-LAST:event_strippedButtonActionPerformed

    private void orangeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orangeButtonActionPerformed
        player.setShirt("orange");
        checker();
    }//GEN-LAST:event_orangeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orangeButton;
    private javax.swing.JButton strippedButton;
    private javax.swing.JButton walkingdeadButton;
    // End of variables declaration//GEN-END:variables
}
