/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import Classes.Boyfriend;
import java.io.File;

/**
 *
 * @author Asus
 */
public class TitleScreen extends javax.swing.JFrame {

    private MainScreen mainScreen;
    Boyfriend player;
    String line, name = "Jacob", shirt = "striped", theme = "normal", position = "center";
    int food = 100, fun = 100, sleep = 100, attention = 100;

    public TitleScreen() {
        initComponents();

       // try {
         //   FileReader fr = new FileReader("src//DataFiles//SaveFile.txt");
          //  BufferedReader br = new BufferedReader(fr);

         //   line = br.readLine();

         //   System.out.println("file read");
//
         //   if (line == null) {
         //       br.close();
          //      System.out.println("line closed");
          //  } else {
          //      int counter = 0;
           //     boolean flag = false;
           //     shirt = line;

           //     while (flag == false) {
           //         line = br.readLine();
            //        counter++;

             //       System.out.println(counter);
             //       if (line == null) {
             //           br.close();
             //           flag = true;
             //           System.out.println("line closed new value");
             //       } else if (counter == 1) {
               //         theme = line;
              //      } else if (counter == 2) {
              //          name = line;
              //      } else if (counter == 3) {
              //          position = line;
               ///     } else if (counter == 4) {
               //         food = Integer.parseInt(line);
                //    } else if (counter == 5) {
                //        fun = Integer.parseInt(line);
                //    } else if (counter == 6) {
                //        sleep = Integer.parseInt(line);
                 //   } else if (counter == 7) {
                 //       attention = Integer.parseInt(line);
                //    }

               // }
          //  }

      //  } catch (IOException e) {

         //   System.out.print("Error: " + e);
      //  }

       player = new Boyfriend(shirt, theme, position, name, fun, attention, food, sleep);

       // File f = new File("src//DataFiles//SaveFile.txt");
       // f.delete();
       // System.out.println("file deleated");
    }

    public Boyfriend getPlayer() {
        return player;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(null);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);
        startButton.setBounds(210, 480, 180, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/intro screen.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed

        if (mainScreen == null) {
            mainScreen = new MainScreen(this);
        }
        mainScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TitleScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
